OctoAwesome/octoawesome

- OctoAwesome/OctoAwesome/OrientationFlags.cs
Standardmäßig sind enums ein int. Die OrientationFalgs passen aber in ein byte.
> OrientationFlags als byte

- OctoAwesome/OctoAwesome/ChunkCache.cs
- OctoAwesome/OctoAwesome/ChunkLoader.cs
Wir haben bei unserer Performance-Session vor 14 Tagen vergessen, dass der ChunkLoader nicht mehr benötigte Chunks wieder freigibt. Andernfalls wiederholen sich die Chunks, wenn man eine Weile in eine Richtung läuft.
> [Hotfix] ChunkLoader Chunks freigeben

- OctoAwesome/OctoAwesome.Client/Components/SceneComponent.cs
Die SceneComponent hat nur 1 und den selben ChunkRenderer versucht neu zu laden.
Wenn wir nun über alle ChunkRenderer iterieren, die ein Update benötigen, wird die Welt wieder gerendert.
Ist sicherlich nicht die performanteste Lösung, aber sie scheint erstmal zu funktionieren.
> Fix: Welt rendert nicht.

- OctoAwesome/OctoAwesome.Runtime/ActorHost.cs
Zusätzlich noch den Zähler für das Abziehen der Blöcke wieder einkommentiert.
> [Issue] Inventar-Stacks des gleichen Typs sorgen für Exception-behoben

- OctoAwesome/OctoAwesome.Client/Components/ChunkRenderer.cs
verhindert Texture bleeding für beliebige Texture größen
> Texture Atlas gap größe auf halben pixel korrigiert

- OctoAwesome/OctoAwesome.Client/Components/ScreenComponent.cs
- OctoAwesome/OctoAwesome.Client/OctoGame.cs
- OctoAwesome/OctoAwesome.Client/Screens/MainScreen.cs
- OctoAwesome/OctoAwesome.ModTestPlugin/OctoAwesome.ModTestPlugin.csproj
- OctoAwesome/OctoAwesome.ModTestPlugin/Properties/AssemblyInfo.cs
- OctoAwesome/OctoAwesome.ModTestPlugin/TestPlugin.cs
- OctoAwesome/OctoAwesome.Runtime/PluginManager.cs
- OctoAwesome/OctoAwesome.sln
- OctoAwesome/OctoAwesome/ActionManager.cs
- OctoAwesome/OctoAwesome/IPlugin.cs
- OctoAwesome/OctoAwesome/OctoAwesome.csproj
Simple API (Quick & dirty mit object-Polymorphie) zum Modding der Benutzeroberfläche. Beispielhaft implementiert am Hauptmenü.
Folgende Klassen und Schnittstellen sind neu:
* `IPlugin`: Basisschnittstelle für Plugins
* `PluginManager`: verwaltet Plugins und ruft deren einzige Methode beim Start auf.
* `ActionManager`: Verwaltet Aktionen und führt diese aus.
Beispielimplementierung siehe `OctoAwesome.ModTestPlugin`.
Die Funktionweise mit object[] als Parameter ist nicht wirklich gut, aber MonoGameUi ist im OctoAwesome-Projekt nicht bekannt. Durch die Typüberprüfung werden aber trotzdem Casts zu falschen Typen (auf Grund von Plugin-Fehlern) recht gut unterbunden.
> UIMod & Action API

- OctoAwesome/OctoAwesome.Runtime/OctoAwesome.Runtime.csproj
- OctoAwesome/OctoAwesome/OctoAwesome.csproj
Sorry, habe ich beim letzten Pull Request vergessen. Sonst buildet die Hilfe nicht bzw. ohne Kommentare.
> Hilfedatei als xml generieren und Warnungen bzgl. fehlender Dokumentationskommentare unterdrücken

- OctoAwesome/OctoAwesome.Basics/Definitions/Trees/BirchTreeDefinition.cs
- OctoAwesome/OctoAwesome.Basics/Definitions/Trees/OakTreeDefinition.cs
- OctoAwesome/OctoAwesome.Basics/Definitions/Trees/SpruceTreeDefinition.cs
- OctoAwesome/OctoAwesome.Basics/ITreeDefinition.cs
- OctoAwesome/OctoAwesome.Basics/TreeDefinition.cs
- OctoAwesome/OctoAwesome.Basics/TreePopulator.cs
Zweiter Ansatz für temperaturabhängige Bäume.
Es gab wieder inkonsistente Zeilenenden (habs aber weggeklickt). Das heißt übrigens nicht, dass nur LF statt CRLF verwendet wird, sondern dass innerhalb der Datei gemischt wird. Anscheinend hat VS so seine Probleme mit Dateien mit LF und fügt dann neue Zeilen mit CRLF hinzu (und meckert später dann):
Gestern haben wir uns ja auf CRLF als Lineending geeinigt. Bei git gibt es jetzt zwei Möglichkeiten:
1. Alle (!) schalten mit `git config core.autocrlf false` die automatische Konvertierung aus, du gehts alle Dateien durch und konvertierst sie zu CRLF und commitest dann. Git macht dann keine automatischen Veränderungen an den Zeilenenden und alle haben nur CRLF Dateien. Problem: Wenn einer von Linux commitet und eine LF Datei eincheckt, dann …
> Bäume temperaturabhängig setzen

- OctoAwesome/OctoAwesome.Client/Components/KeyMapper.cs
- OctoAwesome/OctoAwesome.Client/Components/PlayerComponent.cs
- OctoAwesome/OctoAwesome.Client/OctoGame.cs
- OctoAwesome/OctoAwesome.Client/Screens/BaseScreen.cs
- OctoAwesome/OctoAwesome.Client/Screens/GameScreen.cs
- OctoAwesome/OctoAwesome.Client/Screens/MessageScreen.cs
- OctoAwesome/OctoAwesome.Client/Screens/OptionsScreen.cs
- OctoAwesome/OctoAwesome/SettingsManager.cs
* Alle Tasten aus den `OnKeyDown/Up/Press` Methoden in den `KeyMapper` umgezogen.
* Den `KeyMapper` um ein paar kleine Funktionalitäten (Laden von Standardwerten und aus der Konfiguration, alle Bindings zurückgeben) erweitert.
* `OptionsScreen` um ein `TabControl` erweitert, zwei Tabs (Options, Bindings) eingeführt.
* Simples UI für das Zuweisen von Keys zu Bindings.
**ABER:**
* Es geht bis jetzt nur ein Key pro Binding
Außerdem möchte ich noch von @fnawratil wissen, ob ihm das so passt, ist ja schließlich sein KeyMapper.
**EDIT:** Ich habe erst jetzt bemerkt, dass es zu Konflikten mit der Escape Taste kommt (`BaseScreen` und `GameScreen`). Daher navigiert jetzt Backspace zum letzten Screen, nicht mehr Esc (aber noch nicht über den KeyMapper anpassbar). Esc kehrt wie gewohnt zum …
> UI für KeyMapper

- OctoAwesome/OctoAwesome.Client/OctoGame.cs
Änderungen:
* Ausblenden aller Controls jetzt mit `F9`
* Full Screen Modus mit `F11`
Sollte eigentlich auf allen Plattformen funktionieren, benutzt ja keine Windows features. Bei Multimonitor Betrieb könnte es Probleme geben, kann ich aber mangels mehrerer Monitore nicht überprüfen. Vielleicht kann @tomwendel das mal machen.
> FullScreen Modus implementiert

- OctoAwesome/OctoAwesome.Client/Assets/OctoAwesome.Client/Crew/crew.xml
- OctoAwesome/OctoAwesome.Client/CrewMember.cs
- OctoAwesome/OctoAwesome.Client/Languages/OctoClient.Designer.cs
- OctoAwesome/OctoAwesome.Client/Languages/OctoClient.de.resx
- OctoAwesome/OctoAwesome.Client/Languages/OctoClient.resx
- OctoAwesome/OctoAwesome.Client/Screens/CrewMemberScreen.cs
* CrewMember um Links erweitert
* Crew mit Wiki abgeglichen
* Crew-Seite im Wiki wird per JS aus der XML-Datei generiert: https://github.com/ManuelHu/octocrew-js
* EDIT: Jetzt werden auch die Links im CrewMemeberScreen angezeigt - nach einer Sicherheitsüberprüfung, damit uns keiner auf ein Programm verlinkt und das dann gestartet wird.
> Crew per JS im Wiki

- OctoAwesome/OctoAwesome.Docs/OctoAwesome.Docs.csproj
Beim nächsten Merge mit dem master erhält dieser auch den Fix.
> DocFX log.txt im Ausgabeverzeichnis generieren

- OctoAwesome/OctoAwesome.Client/Controls/OptionsOptionControl.cs
- OctoAwesome/OctoAwesome.Client/OctoGame.cs
- OctoAwesome/OctoAwesome.Client/Screens/LoadScreen.cs
- OctoAwesome/OctoAwesome.Runtime/ResourceManager.cs
- OctoAwesome/OctoAwesome.Tests/OctoAwesome.Tests.csproj
- OctoAwesome/OctoAwesome.Tests/SettingsManagerTests.cs
- OctoAwesome/OctoAwesome/ISettings.cs
- OctoAwesome/OctoAwesome/Settings.cs
- Neben `default(T)` können eigenen Default-Werte angegeben werden - das spart uns einige `KeyExists`-Aufrufe.
- Löschen von Keys ist jetzt möglich (aber noch kein Einsatzgebiet)
- Tests erweitert (`Nulltest` => `UnsetTest`, neuer `DeleteTest`)
- Die neuen Funktionen werden auch schon im `OctoGame`, dem `ResourceManager` und den Screens eingesetzt.
Siehe auch #166
> Settings erweitert

- OctoAwesome/OctoAwesome.Client/Screens/LoadScreen.cs
- OctoAwesome/OctoAwesome.Client/Screens/TargetScreen.cs
* Doppelklick auf Universe-Liste startet Spiel
* Das Label im LoadScreen rechts oben zeigt auch den Seed an
* Man kann mit `Esc` den TargetScreen verlassen (und muss sich nicht mehr sinnlos hoch teleportieren)
fixes #137
> Kleine UI-Verbesserungen

- OctoAwesome/OctoAwesome.Basics/Definitions/Items/PickAxeDefinition.cs
- OctoAwesome/OctoAwesome.Basics/Definitions/Items/WauziEggDefinition.cs
- OctoAwesome/OctoAwesome.Basics/SimulationComponents/BlockInteractionComponent.cs
- OctoAwesome/OctoAwesome.Client/Components/PlayerComponent.cs
- OctoAwesome/OctoAwesome.Client/OctoGame.cs
- OctoAwesome/OctoAwesome.Client/Screens/GameScreen.cs
- OctoAwesome/OctoAwesome.Client/Screens/InventoryScreen.cs
- OctoAwesome/OctoAwesome/BlockDefinition.cs
- OctoAwesome/OctoAwesome/EntityComponents/InventoryComponent.cs
- OctoAwesome/OctoAwesome/EntityComponents/ToolBarComponent.cs
- OctoAwesome/OctoAwesome/IBlockDefinition.cs
- OctoAwesome/OctoAwesome/IInventoryableDefinition.cs
- OctoAwesome/OctoAwesome/IItemDefinition.cs
- OctoAwesome/OctoAwesome/InventorySlot.cs
- OctoAwesome/OctoAwesome/OctoAwesome.csproj
Ziel dieses PR ist das Zentralisieren von Methoden zum Manipulieren des Inventars. Bisher waren diese (teilweise sehr fehlerbehaftet, vgl. #155  #193) an den jeweiligen Stellen der Manipulation implementiert. 
Jetzt sind sie in den entsprechenden `EntityComponents` vorhanden, die auch die Daten halten: `ToolBarComponent` und `InventoryComponent`. Die beiden oben genannten, das Inventar/die Toolbar betreffenden Issues wurden gefixt.
Zur Vereintheitlichung wurde ein neues Interface `IInventoryableDefinition` eingeführt, das für das Inventar benötigte Informationen enthält (Volumen, Limits). Diese waren bisher nur in den Spezialisierungen enthalten und waren nicht zugreifbar und damit nicht in den Manipulationsmethoden nicht erreichbar (erschwerte #193).
fixes #155, #193, #210
> Inventar: Zentrale Verwaltungsmethoden

- OctoAwesome/OctoAwesome.Basics/ComplexPlanet.cs
- OctoAwesome/OctoAwesome.Basics/ComplexPlanetGenerator.cs
- OctoAwesome/OctoAwesome.Basics/DebugMapGenerator.cs
- OctoAwesome/OctoAwesome.Basics/SimulationComponents/NewtonGravitatorComponent.cs
- OctoAwesome/OctoAwesome.Client/Controls/DebugControl.cs
- OctoAwesome/OctoAwesome.Tests/TestPlanet.cs
- OctoAwesome/OctoAwesome/Coordinate.cs
- OctoAwesome/OctoAwesome/IPlanet.cs
- OctoAwesome/OctoAwesome/Planet.cs
fixes #220 
Die Schnittstelle `IPlanet` bekommt das schon länger im `Planet` vorhandene Property `Gravity`. In der entsprechenden Gravitator-Komponente wird dann auch die Angabe aus dem Planet verwendet.
Daneben wird die Gravitation anhand der Planetengröße berechnet. Unsere Derzeit verwendete Planetengöße 2¹² x 2¹² Blöcke entspricht dabei gravitativ annähernd der Erde.
> Use gravity constant from planet

- OctoAwesome/OctoAwesome.Basics/SimulationComponents/BlockInteractionComponent.cs
- OctoAwesome/OctoAwesome.Client/Components/ChunkRenderer.cs
Jetzt werden die korrekten globalen IDs verwendet
> Fix texture rotation & offsets. Re-enable oriented block placement

- OctoAwesome/OctoAwesome.Network.Tests/ServerTests.cs
- OctoAwesome/OctoAwesome.Tests/TestGlobalCache.cs
Hallo zusammen, ich habe in den Projekten `OctoAwesome.Network.Tests` und `OctoAwesome.Tests` Fehler behoben damit man `develop` wieder erfolgreich bauen kann.
- In `OctoAwesome.Network.Tests.ServerTests` den Aufruf von `server.Start(IPAddress.Any, 44444)` zu `server.Start(new IPEndPoint(IPAddress.Any, 44444))` umgeändert
- In `OctoAwesome.Tests.TestGlobalCache` die fehlenden Schnittstellenmember von `IGlobalChunkCache` mit `throw new NotImplementedException()` implementiert
> Kompilierungsprobleme in den Testprojekten behoben

- OctoAwesome/OctoAwesome.Basics/SimulationComponents/MoveComponent.cs
Wauzi hat geflackert wenn man stillgestanden ist. Das lag an den externen Kräften, da der Spieler aktuell nie richtig auf einer Position stehen bleibt.
> Fix wauzi flicker when standing still

- OctoAwesome/OctoAwesome.Basics/SimulationComponents/MoveComponent.cs
- OctoAwesome/OctoAwesome.Client/Components/ChunkRenderer.cs
- OctoAwesome/OctoAwesome.Client/Controls/DebugControl.cs
- OctoAwesome/OctoAwesome.Client/Screens/GameScreen.cs
- OctoAwesome/OctoAwesome.Database/Defragmentation.cs
- OctoAwesome/OctoAwesome.Database/GuidTag.cs
- OctoAwesome/OctoAwesome.Database/ITag.cs
- OctoAwesome/OctoAwesome.Database/IdTag.cs
- OctoAwesome/OctoAwesome.Database/Key.cs
- OctoAwesome/OctoAwesome.Database/KeyStore.cs
- OctoAwesome/OctoAwesome.Database/OctoAwesome.Database.csproj
- OctoAwesome/OctoAwesome.Database/ValueStore.cs
- OctoAwesome/OctoAwesome.Database/Writer.cs
- OctoAwesome/OctoAwesome/Chunk.cs
- OctoAwesome/OctoAwesome/ChunkColumn.cs
- OctoAwesome/OctoAwesome/GlobalChunkCache.cs
- OctoAwesome/OctoAwesome/Serialization/ChunkColumnDbContext.cs
- OctoAwesome/OctoAwesome/Serialization/ChunkDiffTag.cs
- OctoAwesome/OctoAwesome/Serialization/Index2Tag.cs
- OctoAwesome/OctoAwesome/Serialization/Index3Tag.cs
- OctoAwesome/OctoAwesome/Serialization/Serializer.cs
- OctoAwesome/OctoAwesome/Startup.cs
- OctoAwesome/Tests/OctoAwesome.Database.Tests/KeyTests.cs
* to save on garbage collection of the arrays and because we know the size beforehand, so we can allocate it on the stack
* Use chunkpool, which was already implemented but not correctly used, because get and push was never called
* Removed linq from MoveComponent, which did create a class on the heap, even tho it wasn't required
* Made stackalloc array in Chunkrenderer to be saved in a span, so no unsafe context is needed
> Reworked Tag saving to use span instead of returning byte array

- OctoAwesome/OctoAwesome.Basics/OctoAwesome.Basics.csproj
- OctoAwesome/OctoAwesome.Client.UI/Controls/CrosshairControl.cs
- OctoAwesome/OctoAwesome.Client.UI/Controls/GroupBox.cs
- OctoAwesome/OctoAwesome.Client.UI/Controls/Line.cs
- OctoAwesome/OctoAwesome.Client.UI/OctoAwesome.Client.UI.csproj
- OctoAwesome/OctoAwesome.Client/Control/OptionsOptionControl.cs
- OctoAwesome/OctoAwesome.Client/OctoAwesome.Client.csproj
- OctoAwesome/OctoAwesome.Client/Screens/BaseScreen.cs
- OctoAwesome/OctoAwesome.Client/Screens/CreateUniverseScreen.cs
- OctoAwesome/OctoAwesome.Client/Screens/GameScreen.cs
- OctoAwesome/OctoAwesome.Community/OctoAwesome.Community.csproj
- OctoAwesome/OctoAwesome.Database/OctoAwesome.Database.csproj
- OctoAwesome/OctoAwesome.Docs/OctoAwesome.Docs.csproj
- OctoAwesome/OctoAwesome.GameServer/OctoAwesome.GameServer.csproj
- OctoAwesome/OctoAwesome.Network/OctoAwesome.Network.csproj
- OctoAwesome/OctoAwesome/OctoAwesome.csproj
- GroupBox Control hinzugefügt
- Line Control hinzugefügt (mal eine einfache Linie)
- Erlaubt das drücken von Esc wenn man im Menü zurück navigieren möchte(ich fande Backspace sehr unintuitiv)
- Beim Erstellen eines neuen Universums wird nun die Textbox für den Universums-Namen fokusiert, mit Tab kann man nun in die Seed Textbox springen
- Fügt Optionen hinzu mit denen man sofort(ohne das Spiel neuzustarten, oder das Universum neuzuladen), die Eigenschaften des Crosshair Controls abändern kann
- Man kann nun die Größe einstellen (Ich habe es nie richtig gesehen)
- Man kann nun die Farbe aus 5 verschiedenen Optionen auswählen (engenious hat kein Colorpicker Control)
- Ich weiß nicht genau, wie das bisherige Speichern der Optionen funktioniert hat und habe es auch nicht verstanden. Daher …
> Kleinere Lebensqualitäts(QOL) Verbesserungen
