OctoAwesome/octoawesome

OctoAwesome/OctoAwesome.Runtime/ActorHost.cs
OctoAwesome/OctoAwesome/Player.cs

Fix: Power and Force

---

OctoAwesome/OctoAwesome.Client/Components/Input/KeyboardInput.cs
OctoAwesome/OctoAwesome.Client/Components/SimulationComponent.cs

Fix der KeyboardInputComponent und des Ladens bei keiner vorhandenen player.info-Datei

Zwei Fixes

---

OctoAwesome/OctoAwesome.Client/Components/HudComponent.cs

Das nervt etwas das ich immer mit dem Probleme hab

aus hud das Hud gemacht das nervt etwas unter Linux ^^

---

OctoAwesome/OctoAwesome.Basics/GrassBlockDefinition.cs
OctoAwesome/OctoAwesome.Basics/GroundBlockDefinition.cs
OctoAwesome/OctoAwesome.Basics/SandBlockDefinition.cs
OctoAwesome/OctoAwesome.Basics/StoneBlockDefinition.cs
OctoAwesome/OctoAwesome.Basics/WaterBlockDefinition.cs
OctoAwesome/OctoAwesome.Basics/WoodBlockDefinition.cs
OctoAwesome/OctoAwesome/PhysicalProperties.cs

kann später zur Berchnung von benötigten Leistungen von Maschinen sein

reale Dichten für die Blöcke übernommen

---

OctoAwesome/OctoAwesome.Client/Components/SceneComponent.cs

So hab dein Fehler mit der Sonne und der Zeit behoben. Es richtet sich nun nach der aktuellen UTC-Zeit auf dem System. Das Problem war anscheind das die Zahl zugroß war für die Funktion.

Fehler mit der UTC Sonne behoben

---

OctoAwesome/OctoAwesome.Runtime/ActorHost.cs
OctoAwesome/OctoAwesome/Entity.cs
OctoAwesome/OctoAwesome/Player.cs

Es sollte das problem mit dem einfriren beim laden von Chunksbeheben und lagert die Bewegungsberechnung in eine eigene Methode aus

Physik und Actorhost Patch

---

OctoAwesome/OctoAwesome.Client/OctoAwesome.Client.csproj
OctoAwesome/OctoAwesome.Client/Screens/ConnectScreen.cs
OctoAwesome/OctoAwesome.Client/Screens/MainScreen.cs
OctoAwesome/OctoAwesome.Client/Screens/OptionsScreen.cs

Einfacher ConnectScreen eingefügt...
Mit Shift+Multiplayer sollte man sich direkt mit einem Server verbinden können (Debugging),
das ist aber noch nicht *fertig* implementiert...
Mfg rave

Added ConnectScreen

---

OctoAwesome/OctoAwesome.Client/Screens/ConnectScreen.cs

Refined Connect Screen

---

OctoAwesome/OctoAwesome.Client/Screens/SinglePlayerScreen.cs
OctoAwesome/OctoAwesome.Server/MainForm.Designer.cs
OctoAwesome/OctoAwesome.Server/MainForm.cs

Server Window sieht jetzt so aus:
Momentan läuft nur der Stop Knopf (der dann zum Start Knopf wird)...
(Der aber auch nur unsauber gelöst, weil ich den aktuellen state nicht abfragen kann)
Mfg rave

Refined Server Window

---

OctoAwesome/OctoAwesome.Server/MainForm.Designer.cs
OctoAwesome/OctoAwesome.Server/MainForm.cs
OctoAwesome/OctoAwesome.Server/OctoAwesome.Server.csproj
OctoAwesome/OctoAwesome.Server/ServerConsole.cs

Einfache Server-Console hinzugefügt.
Kann momentan nur loggen

Added Server Console

---

OctoAwesome/OctoAwesome.Client/Controls/ConsoleControl.cs
OctoAwesome/OctoAwesome.Client/Controls/DebugControl.cs
OctoAwesome/OctoAwesome.Client/OctoAwesome.Client.csproj
OctoAwesome/OctoAwesome.Client/Screens/GameScreen.cs
OctoAwesome/OctoAwesome.Server/MainForm.cs
OctoAwesome/OctoAwesome.Server/OctoAwesome.Server.csproj
OctoAwesome/OctoAwesome.Server/ServerConsole.cs

Einfache Server-Console wieder hinzugefügt.
Jetzt ThreadSafe
Mfg rave

Server-Console & Client-Console

---

OctoAwesome/OctoAwesome.Community/OctoAwesome.Community.csproj
OctoAwesome/OctoAwesome.Help/OctoAwesome.Help.shfbproj
OctoAwesome/OctoAwesome.sln

Zur Generierung der Hilfeseiten verwendetes Projekt.

Sandcastle Project

---

OctoAwesome/OctoAwesome.Client/Controls/SceneControl.cs
OctoAwesome/OctoAwesome.Client/OctoGame.cs
OctoAwesome/OctoAwesome.Client/Program.cs
OctoAwesome/OctoAwesome.Client/Screens/CreateUniverseScreen.cs
OctoAwesome/OctoAwesome.Client/Screens/LoadScreen.cs
OctoAwesome/OctoAwesome.Client/Screens/OptionsScreen.cs
OctoAwesome/OctoAwesome.Runtime/DiskPersistenceManager.cs
OctoAwesome/OctoAwesome.Runtime/ResourceManager.cs
OctoAwesome/OctoAwesome/OctoAwesome.csproj
OctoAwesome/OctoAwesome/SettingsManager.cs

* Settingsscreen aufgeräumt (Löschen der Spielstände geht jetzt ja übers Menü)
* `SettingsManager` eingeführt (jaaaa, ich weiß, statische Managers haben wir schon so viele) hinzugefügt. Der ist eigentlich nur eine vereinfachte API um den ConfigurationManager. Vielleicht kann man ihn ja irgendwann auch z.B. fürs Synchronisieren mit Nutzerkontenservern benutzen o.ä.

Settings überarbeitet

---

OctoAwesome/OctoAwesome.Client/Assets/OctoAwesome.Client/Crew/crew.xml

Sorry, wegen der 3 Pull Requests...

Crew aktualisiert

---

OctoAwesome/OctoAwesome.Basics/Definitions/Trees/BirchTreeDefinition.cs

Zweiter Versuch

---

OctoAwesome/OctoAwesome.Client/App.config
OctoAwesome/OctoAwesome.Client/Components/SimulationComponent.cs
OctoAwesome/OctoAwesome.Client/Screens/BaseScreen.cs
OctoAwesome/OctoAwesome.Client/Screens/CreateUniverseScreen.cs
OctoAwesome/OctoAwesome.Client/Screens/LoadScreen.cs
OctoAwesome/OctoAwesome.Runtime/ResourceManager.cs
OctoAwesome/OctoAwesome.Runtime/Simulation.cs
OctoAwesome/OctoAwesome/LocalBuilder.cs
OctoAwesome/OctoAwesome/SettingsManager.cs

Dazu ein paar Veränderungen:
* Alle Methoden, die ein neues Universum erzeugen geben jetzt seine Guid zurück.
* Kleiner Bugfix im `SettingsManager`.
* Die Hervorhebungsfarbe des aktuellen Elements im `LoadScreen` ist jetzt ein ähnliches Braun wie bei den Buttons.
Doku:
* @tomwendel Bitte unbedingt mal im `IMapPopulator` und `MapPopulator` die `column00-11` dokumentieren. Ebenfalls bitte den `LocalBuilder` kommentieren, ich weiß nicht was der macht, weil ich da nicht da war im Stream.

Im LoadScreen immer das letzte Universe auswählen.

---

OctoAwesome/OctoAwesome.Runtime/EntityHost.cs
OctoAwesome/OctoAwesome/IPlanet.cs
OctoAwesome/OctoAwesome/Planet.cs

So jetzt auch nur die 3 Files die auch geändert wurden... Muss noch herausfinden wie das funktioniert mit git und so...

Gravitation in den Planetet (Jetzt richtig)

---

OctoAwesome/OctoAwesome.Client/Screens/BaseScreen.cs
OctoAwesome/OctoAwesome.Runtime/EntityHost.cs
OctoAwesome/OctoAwesome.Runtime/Simulation.cs
OctoAwesome/OctoAwesome.sln
OctoAwesome/OctoAwesome/Entities/CollidableEntity.cs
OctoAwesome/OctoAwesome/Entities/ControllableEntity.cs
OctoAwesome/OctoAwesome/Entities/Dog.cs
OctoAwesome/OctoAwesome/Entities/IBody.cs
OctoAwesome/OctoAwesome/Entities/ICollidable.cs
OctoAwesome/OctoAwesome/Entities/IControllable.cs
OctoAwesome/OctoAwesome/Entities/IMoving.cs
OctoAwesome/OctoAwesome/Entities/IPosition.cs
OctoAwesome/OctoAwesome/Entities/IRotatable.cs
OctoAwesome/OctoAwesome/Entities/MovingEntity.cs
OctoAwesome/OctoAwesome/Entities/PermanentEntity.cs

Doku kommt erst nach Merge mit master auf http://doc.octoawesome.net. `EntityCache` habe ich noch nicht dokumentiert, weil der ja noch nicht fertig ist.

Doku für feature/NPCs

---

OctoAwesome/OctoAwesome.Client/Components/PlayerComponent.cs
OctoAwesome/OctoAwesome.Client/Components/SimulationComponent.cs
OctoAwesome/OctoAwesome.Client/Screens/CreateUniverseScreen.cs
OctoAwesome/OctoAwesome.Client/Screens/LoadScreen.cs
OctoAwesome/OctoAwesome.Runtime/ActorHost.cs
OctoAwesome/OctoAwesome.Runtime/EntityHost.cs
OctoAwesome/OctoAwesome.Runtime/Simulation.cs
OctoAwesome/OctoAwesome/ILocalChunkCache.cs
OctoAwesome/OctoAwesome/LocalChunkCache.cs

vgl. #124.
Es musste über ein Callback gelöst werden, da sonst die `ChunkColumns` noch nicht geladen sind.

BeamUp beim Erstellen der Welt.

---

OctoAwesome/OctoAwesome.Runtime/ActorHost.cs

Fix #134 (Blöcke in sich selbst setzbar)

---

OctoAwesome/OctoAwesome/Entity.cs
OctoAwesome/OctoAwesome/Player.cs

- Dokukommentare aktualisiert & hinzugefügt
- Alte [XmlIgnores] und usings aus Player und Entity entfernt

Inventar Doku

---

OctoAwesome/OctoAwesome.Client/OctoGame.cs
OctoAwesome/OctoAwesome.Client/Screens/OptionsScreen.cs
OctoAwesome/OctoAwesome.Tests/OctoAwesome.Tests.csproj
OctoAwesome/OctoAwesome.Tests/SettingsManagerTests.cs

Habe die neuen "Features", die der SettingsManager jetzt kann, mal in OctoAwesome eingefügt und getestet.

Integration der neuen Features des SettingsManager in OctoAwesome.

---

OctoAwesome/OctoAwesome.Client/Controls/ExtensionsOptionControl.cs
OctoAwesome/OctoAwesome.Client/OctoAwesome.Client.csproj
OctoAwesome/OctoAwesome.Client/OctoGame.cs
OctoAwesome/OctoAwesome.Client/Screens/OptionsScreen.cs
OctoAwesome/OctoAwesome.Runtime/ExtensionLoader.cs
OctoAwesome/OctoAwesome.Tests/SettingsManagerTests.cs
OctoAwesome/OctoAwesome/IExtensionLoader.cs
OctoAwesome/OctoAwesome/Settings.cs

Andere Änderungen:
* `ExtensionLoader` erweitert um Listen und Hilfsmethode zum aktualisieren der Settings
* `NotImplementedExeption` beim Start durch zurückgeben einer leeren List entfernt (muss im nächsten Stream dann richtig implemnetiert werden)

Simple Extensions UI

---

OctoAwesome/OctoAwesome.Runtime/OctoAwesome.Runtime.csproj

Fix Config Bug in OctoAwesome.Runtime

HotFix: OctoAwesome.Runtime Config

---

OctoAwesome/OctoAwesome.Basics/ComplexPlanetGenerator.cs
OctoAwesome/OctoAwesome.Basics/DebugMapGenerator.cs
OctoAwesome/OctoAwesome.Client/Components/ChunkRenderer.cs
OctoAwesome/OctoAwesome.Client/Components/VertexPositionNormalTextureLight.cs
OctoAwesome/OctoAwesome.Client/Content/simple/simple.ps
OctoAwesome/OctoAwesome.Client/Content/simple/simple.vs
OctoAwesome/OctoAwesome.Client/Controls/SceneControl.cs
OctoAwesome/OctoAwesome.Client/Languages/OctoKeys.Designer.cs
OctoAwesome/OctoAwesome.Client/Languages/OctoKeys.resx
OctoAwesome/OctoAwesome.Client/OctoAwesome.Client.csproj
OctoAwesome/OctoAwesome.Client/OctoGame.cs
OctoAwesome/OctoAwesome.Client/Screens/GameScreen.cs
OctoAwesome/OctoAwesome/Chunk.cs
OctoAwesome/OctoAwesome/Wall.cs

Implemented Ambient Occlusion

---

.github/install-mesa-windows.ps1
.github/workflows/ci.yml
OctoAwesome/OctoAwesome.Client.UI/Controls/CrosshairControl.cs
OctoAwesome/OctoAwesome.Client/OctoAwesome.Client.csproj

Adds CI for PRs targeting `master` and `develop`.
Publishes client and server builds for linux and windows to the action artifacts.
special thanks to @jvbsl for helping me out

Working CI 🥳 
